name: Prettier-Linter

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Install npm v8
        run: npm i -g npm@8

      - name: Check code-style
        uses: creyD/prettier_action@v4.2
        with:
          commit_message: "[action] Prettified Code"

